name: Windows MSYS

on: [push, pull_request]

env:
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - target_arch: x86_64
           compiler: gcc
           upload: 1
         - target_arch: x86_64
           compiler: clang
           upload: 0
    env:
      TARGET_ARCH: ${{ matrix.target_arch }}
      COMPILER: ${{ matrix.compiler }}
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          ccache
          clang
          cmake
          git
          make
          pkgconf
          python3
          mingw-w64-${{ matrix.target_arch }}-binutils
          mingw-w64-${{ matrix.target_arch }}-ccache
          mingw-w64-${{ matrix.target_arch }}-clang
          mingw-w64-${{ matrix.target_arch }}-cmake
          mingw-w64-${{ matrix.target_arch }}-ffmpeg
          mingw-w64-${{ matrix.target_arch }}-pkgconf
          mingw-w64-${{ matrix.target_arch }}-qt6
          mingw-w64-${{ matrix.target_arch }}-vlc

    - name: Build
      run: ./ports/ci/windows-msys/build.sh

    - name: Deploy
      run: ./ports/ci/windows-msys/deploy.sh

    # Upload build artifacts so you can download
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webcamoid-windows-build-${{ matrix.target_arch }}-${{ matrix.compiler }}
        path: webcamoid-packages/windows/*
