name: Build Webcamoid (Windows)

on:
  workflow_dispatch:  # lets you trigger manually
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt (5.15.2)
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webcamoid-windows
          path: build/bin/**
