name: Windows MSVC

on: [push, pull_request, workflow_dispatch]

env:
  QTVER: 6.7.2
  FFMPEG_VERSION: 7.0.1
  GSTREAMER_VERSION: 1.24.5
  CMAKE_GENERATOR: Visual Studio 17 2022
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./ports/ci/windows-msvc/install_deps.bat
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: ./ports/ci/windows-msvc/build.bat
    - name: Release Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: ./ports/ci/windows-msvc/deploy.bat
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: ./ports/ci/windows-msvc/build.bat
    - name: Daily Deploy
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: ./ports/ci/windows-msvc/deploy.bat
